// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-demo/internal/biz"
	"kratos-demo/internal/conf"
	"kratos-demo/internal/data"
	"kratos-demo/internal/server"
	"kratos-demo/internal/service"
)

// Injectors from wire.go:

func wireApp(serverConf *conf.Server, dataConf *conf.Data, aiConf *conf.AI, runtimeConf *conf.Runtime, logger log.Logger) (*kratos.App, func(), error) {
	taskRepo := data.NewTaskRepo(logger)
	delegationTraceStore := data.NewDelegationTraceStore()
	agentMemoryStore, err := data.NewAgentMemoryStore(dataConf, logger)
	if err != nil {
		return nil, nil, err
	}
	agentMemoryConfig := data.NewAgentMemoryConfig(dataConf)
	agentMemoryUsecase, err := data.NewAgentMemoryUsecaseProvider(agentMemoryStore, agentMemoryConfig)
	if err != nil {
		return nil, nil, err
	}
	sessionChangeStore := data.NewSessionChangeStore(dataConf)
	agentRuntime := data.NewAgentRuntime(aiConf, runtimeConf, delegationTraceStore, sessionChangeStore, agentMemoryUsecase, logger)
	taskDispatcher := data.NewTaskDispatcher(taskRepo, agentRuntime, delegationTraceStore, agentMemoryUsecase, logger)
	taskUsecase := biz.NewTaskUsecase(taskRepo, taskDispatcher)
	taskService := service.NewTaskService(taskUsecase)
	agentRuntimeService := service.NewAgentRuntimeService(agentRuntime)
	grpcServer := server.NewGRPCServer(serverConf, taskService, agentRuntimeService, logger)
	dashboardService := service.NewDashboardService(delegationTraceStore, agentRuntime, agentMemoryUsecase, sessionChangeStore, runtimeConf)
	httpServer := server.NewHTTPServer(serverConf, taskService, dashboardService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
