// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/memory/v1/memory.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPromptContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptContextRequest) Reset() {
	*x = GetPromptContextRequest{}
	mi := &file_api_memory_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptContextRequest) ProtoMessage() {}

func (x *GetPromptContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_memory_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptContextRequest.ProtoReflect.Descriptor instead.
func (*GetPromptContextRequest) Descriptor() ([]byte, []int) {
	return file_api_memory_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *GetPromptContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPromptContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetPromptContextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptContextReply) Reset() {
	*x = GetPromptContextReply{}
	mi := &file_api_memory_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptContextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptContextReply) ProtoMessage() {}

func (x *GetPromptContextReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_memory_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptContextReply.ProtoReflect.Descriptor instead.
func (*GetPromptContextReply) Descriptor() ([]byte, []int) {
	return file_api_memory_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *GetPromptContextReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_api_memory_v1_memory_proto protoreflect.FileDescriptor

const file_api_memory_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/memory/v1/memory.proto\x12\rapi.memory.v1\"Q\n" +
	"\x17GetPromptContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"1\n" +
	"\x15GetPromptContextReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2q\n" +
	"\rMemoryService\x12`\n" +
	"\x10GetPromptContext\x12&.api.memory.v1.GetPromptContextRequest\x1a$.api.memory.v1.GetPromptContextReplyB\x1eZ\x1ckratos-demo/api/memory/v1;v1b\x06proto3"

var (
	file_api_memory_v1_memory_proto_rawDescOnce sync.Once
	file_api_memory_v1_memory_proto_rawDescData []byte
)

func file_api_memory_v1_memory_proto_rawDescGZIP() []byte {
	file_api_memory_v1_memory_proto_rawDescOnce.Do(func() {
		file_api_memory_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_memory_v1_memory_proto_rawDesc), len(file_api_memory_v1_memory_proto_rawDesc)))
	})
	return file_api_memory_v1_memory_proto_rawDescData
}

var file_api_memory_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_memory_v1_memory_proto_goTypes = []any{
	(*GetPromptContextRequest)(nil), // 0: api.memory.v1.GetPromptContextRequest
	(*GetPromptContextReply)(nil),   // 1: api.memory.v1.GetPromptContextReply
}
var file_api_memory_v1_memory_proto_depIdxs = []int32{
	0, // 0: api.memory.v1.MemoryService.GetPromptContext:input_type -> api.memory.v1.GetPromptContextRequest
	1, // 1: api.memory.v1.MemoryService.GetPromptContext:output_type -> api.memory.v1.GetPromptContextReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_memory_v1_memory_proto_init() }
func file_api_memory_v1_memory_proto_init() {
	if File_api_memory_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_memory_v1_memory_proto_rawDesc), len(file_api_memory_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_memory_v1_memory_proto_goTypes,
		DependencyIndexes: file_api_memory_v1_memory_proto_depIdxs,
		MessageInfos:      file_api_memory_v1_memory_proto_msgTypes,
	}.Build()
	File_api_memory_v1_memory_proto = out.File
	file_api_memory_v1_memory_proto_goTypes = nil
	file_api_memory_v1_memory_proto_depIdxs = nil
}
