[request_definition]
r = sub, obj, path, cmd

[policy_definition]
p = sub, obj, path, cmd

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && (p.obj == "*" || r.obj == p.obj) && (r.path == "" || p.path == "*" || keyMatch2(r.path, p.path)) && (r.cmd == "" || p.cmd == "*" || r.cmd == p.cmd)
