// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/task/v1/task.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCommand) Reset() {
	*x = TaskCommand{}
	mi := &file_api_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommand) ProtoMessage() {}

func (x *TaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommand.ProtoReflect.Descriptor instead.
func (*TaskCommand) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskCommand) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskCommand) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *TaskCommand) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_api_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

type TaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Result        *TaskResult            `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReply) Reset() {
	*x = TaskReply{}
	mi := &file_api_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReply) ProtoMessage() {}

func (x *TaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReply.ProtoReflect.Descriptor instead.
func (*TaskReply) Descriptor() ([]byte, []int) {
	return file_api_task_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskReply) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *TaskReply) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskReply) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskReply) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_task_v1_task_proto protoreflect.FileDescriptor

const file_api_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x16api/task/v1/task.proto\x12\vapi.task.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\vTaskCommand\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\">\n" +
	"\n" +
	"TaskResult\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"A\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"(\n" +
	"\x0eGetTaskRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\"\xa4\x02\n" +
	"\tTaskReply\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.api.task.v1.TaskResultR\x06result\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x128\n" +
	"\tcreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xcd\x01\n" +
	"\vTaskService\x12^\n" +
	"\n" +
	"CreateTask\x12\x1e.api.task.v1.CreateTaskRequest\x1a\x16.api.task.v1.TaskReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12^\n" +
	"\aGetTask\x12\x1b.api.task.v1.GetTaskRequest\x1a\x16.api.task.v1.TaskReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/tasks/{taskID}B\x1cZ\x1akratos-demo/api/task/v1;v1b\x06proto3"

var (
	file_api_task_v1_task_proto_rawDescOnce sync.Once
	file_api_task_v1_task_proto_rawDescData []byte
)

func file_api_task_v1_task_proto_rawDescGZIP() []byte {
	file_api_task_v1_task_proto_rawDescOnce.Do(func() {
		file_api_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_v1_task_proto_rawDesc), len(file_api_task_v1_task_proto_rawDesc)))
	})
	return file_api_task_v1_task_proto_rawDescData
}

var file_api_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_task_v1_task_proto_goTypes = []any{
	(*TaskCommand)(nil),           // 0: api.task.v1.TaskCommand
	(*TaskResult)(nil),            // 1: api.task.v1.TaskResult
	(*CreateTaskRequest)(nil),     // 2: api.task.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),        // 3: api.task.v1.GetTaskRequest
	(*TaskReply)(nil),             // 4: api.task.v1.TaskReply
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_task_v1_task_proto_depIdxs = []int32{
	1, // 0: api.task.v1.TaskReply.result:type_name -> api.task.v1.TaskResult
	5, // 1: api.task.v1.TaskReply.createdAt:type_name -> google.protobuf.Timestamp
	5, // 2: api.task.v1.TaskReply.updatedAt:type_name -> google.protobuf.Timestamp
	2, // 3: api.task.v1.TaskService.CreateTask:input_type -> api.task.v1.CreateTaskRequest
	3, // 4: api.task.v1.TaskService.GetTask:input_type -> api.task.v1.GetTaskRequest
	4, // 5: api.task.v1.TaskService.CreateTask:output_type -> api.task.v1.TaskReply
	4, // 6: api.task.v1.TaskService.GetTask:output_type -> api.task.v1.TaskReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_task_v1_task_proto_init() }
func file_api_task_v1_task_proto_init() {
	if File_api_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_v1_task_proto_rawDesc), len(file_api_task_v1_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_task_v1_task_proto_goTypes,
		DependencyIndexes: file_api_task_v1_task_proto_depIdxs,
		MessageInfos:      file_api_task_v1_task_proto_msgTypes,
	}.Build()
	File_api_task_v1_task_proto = out.File
	file_api_task_v1_task_proto_goTypes = nil
	file_api_task_v1_task_proto_depIdxs = nil
}
